### ISSUE TITLE
適切なフラッシュメッセージを出す

### ISSUE THREAD

**Issue by yamamoto99** [yamamoto99/es-writer#30]
- ログイン失敗時に失敗したことを示すメッセージがあった方が良さげ
- 登録失敗時もなぜ失敗したのかユーザーはわからない

**Comment by Yutosaki** [comment]
* サインアップの失敗
    * メールアドレスが既に登録されている
    * ユーザーネームが既に登録されている
    * フォームのバリデーションは既にされてそうだからなんもしない
    * ネットワークやサーバー側のエラー（可能なら）
* サインインの失敗
    *ユーザー名かパスワードが間違っている（どっちが間違っているか教えると他の人のやつにアクセス出来ちゃう）
    * ネットワークやサーバー側のエラー（可能なら）
こんなもんかな
